### PR TITLE
feat: added context-path support

### PR DESCRIPTION
**Pull request by skayliu**
we can now have zeebe-simple-takslist running on a different path then ` /`  by setting:
`server.servlet.context-path=/tasklist/`

closes [issues#38](https://github.com/camunda-community-hub/zeebe-simple-tasklist/issues/38)

### CODE REVIEW

**Comment by skayliu** [comment]
Hi,@saig0, I've added context-path support, please have a review it, thank you.

**Comment by saig0** [comment]
@skayliu awesome. :tada: Thank you for contributing. :rocket: 

Please note that I'm less available at the moment. It might take two weeks before a can have a look at your changes.

**Review by saig0 — CHANGES_REQUESTED** [review]
@skayliu nice. :tada: The changes look good. :+1: 

But the notifications don't work anymore. The UI doesn't show a notification if a new task is added or canceled. Maybe, you need to adjust `WebSocketConfig` too. Please have a look. :cookie: 

image

**Comment by skayliu** [comment]
Hi, @saig0, It's done , please check this out.

**Review by saig0 — APPROVED** [review]
@skayliu awesome. :tada: 

Your PR is ready to merge. :rocket:

**Pull request merged**
